services:
  ganache:
    image: trufflesuite/ganache:latest
    command: --db=/var/lib/vodasset/data -d true --account="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80,1000000000000000000000000000"
    ports:
      - 8546:8545
    volumes:
      - sl_vodasset_workshop:/var/lib/vodasset/data
volumes:
  sl_vodasset_workshop:
